### ISSUE TITLE
The output wav file is not usable in python "wave" module. wave.Error: unknown format: 3

### ISSUE THREAD

**Issue by azuredream** [wblgers/py_speech_seg#2] opened 2019-03-14 04:24 UTC
Your output wav file is not usable in python "wave" module. Error message: 
wave.Error: unknown format: 3

I do not know WAV format well , your output file in encoding with "F.P. PCM" while other working-well files are encoding with "Signed PCM".  
![QQ截图20190313121031](https://user-images.githubusercontent.com/7879556/54331080-4b3c8c80-4653-11e9-9be2-eb0b492c20d9.jpg)

I would appreciate it very much if you could help me solve this problem.

**Comment by wblgers** [comment] 2019-03-19 12:28
I recommend you use the cool audio tool 'sox' under linux, you can change the bits and encoding like below:
sox 0.wav -b 16 -e signed-integer 00.wav

You can google more on the use of 'sox' to manipulate the audios.

**Comment by wblgers** [comment] 2019-03-19 12:33
The issue is due to the default setting in the output module of librosa, in this line:
`librosa.output.write_wav("save_audio/%s.wav"%i,tempAudio,sr)`
For librosa.output, refer to the details:
`Note: only mono or stereo, floating-point data is supported.`
So the encoding is "Floating Point PCM" and the quantification bit is 24, you can change them easily by sox like my comment before, you can also insert the "bash command" into the python code like:

`os.system(cmd)`

You can close this issue if above is helpful to you! Thanks!

**Closed as completed** 2019-07-29 08:49 UTC
